### ISSUE TITLE
Fix Navigation

### ISSUE THREAD

**Issue by rhendz** [vjsrinivas/potify#5]
Make sure the user can navigate backwards with the back button.

Furthermore, there were some issues with having to double click using our navigation

**Comment by vjsrinivas** [comment]
Back button issues are probably caused by incorrect routing practices in files like app-routing.module.ts.
Back button component is *not* a simple button and looks in a stack of previous paths that the user has followed in order to determine whether to display or not and what page to go back to.

Refer to possible solution: https://www.joshmorony.com/using-angular-routing-with-ionic-4/
